name = "gleam_fetch"
version = "0.4.0"
licences = ["Apache-2.0"]
description = "Make HTTP requests in Gleam JavaScript with Fetch"
target = "javascript"
gleam = ">= 0.32.0"

repository = { type = "github", user = "gleam-lang", repo = "fetch" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_http = "~> 3.1"
gleam_javascript = "~> 0.3 or ~> 1.0"
gleam_stdlib = "~> 0.32 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"

